[package]
name = "bitcask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", default-features = false }
serde_json = "1.0"
serde = { version = "1.0.217", features = ["derive"] }
clap = { version = "4.5.27", features = ["derive"] }
